pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    paths:
    - public
  only:
  - master
  